### ISSUE TITLE
pvc name - must be no more than 63 characters

### ISSUE THREAD

**Issue by venugopalthati** [BobDotMe/bob#15]
Coming across an error while bringing up pod by using pvc name which is more than 63 characeters.

**with space after --pvc**
```
k bob --pvc prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0 --name promtest
The Pod "promtest" is invalid: 
* spec.volumes[0].name: Invalid value: "bv-prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0": must be no more than 63 characters
* spec.containers[0].volumeMounts[0].name: Not found: "bv-prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0" 
```
**with = after --pvc**
```
k bob --pvc=prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0 --name promtest
The Pod "promtest" is invalid: 
* spec.volumes[0].name: Invalid value: "bv-prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0": must be no more than 63 characters
* spec.containers[0].volumeMounts[0].name: Not found: "bv-prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0"
```

**with -o yaml option**
```
k bob --pvc prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0 --name promtest -o yaml
apiVersion: v1
kind: Pod
metadata:
  name: promtest
  
  labels:
    app: bob
spec:
  terminationGracePeriodSeconds: 20
  containers:
  - image: bobdotme/bob-lowcarb:v0.9.7
    imagePullPolicy: IfNotPresent
    name: promtest
    #ports:
    #- containerPort: 80
    #  name: dummy
    #  protocol: TCP
    resources:
      limits:
        memory: "1Gi"
        cpu: "2"
      requests:
        memory: "1M"
        cpu: "500m"
    volumeMounts:
    
    
    - name: bv-prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0
      mountPath: /vols/prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0
    
    #- name: shared-volume
    #  mountPath: /usr

    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: MY_POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: BOB_SERVICE_NAMESPACE
      value: "bob"
  restartPolicy: Always
  volumes:
  
  
  - name: bv-prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0
    persistentVolumeClaim:
       claimName: prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0

```
